name: Sync Labels from Linear Issue to PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get associated issue number
        id: get-issue-number
        run: |
          ISSUE_NUMBERS=$(echo "${{ github.event.pull_request.body }}" | grep -oE "#[0-9]+" | tr -d "#" | tr '\n' ',')
          ISSUE_NUMBERS=$(echo $ISSUE_NUMBERS | sed 's/,$//')
          echo "ISSUE_NUMBERS=$ISSUE_NUMBERS" >> $GITHUB_ENV
          echo "Issue numbers are $ISSUE_NUMBERS"

      - name: Get labels from issue
        id: get_issue_labels
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumbers = process.env.ISSUE_NUMBERS.split(","); 
            console.log({ issue_number: issueNumbers[0],
            owner: context.repo.owner,
            repo: context.repo.repo}); 
            try {
              const {data:{labels}} = await github.rest.issues.get({
                issue_number: issueNumbers[0],
                owner: context.repo.owner,
                repo: context.repo.repo,
              });
              console.log(labels);
            } catch (error) {
              console.log(`Error: ${error}`);
              return '';
            }
        env:
          ISSUE_NUMBERS: ${{ env.ISSUE_NUMBERS }}

      - name: Apply labels to PR
        if: steps.get_issue_labels.outputs.result != ''
        uses: actions/github-script@v6
        with:
          script: |
            const labels = ${{env.labels}}.split(",");
            echo `Applying labels: ${label.split(",")}`;
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels,
            });
