name: Sync Labels from Issue to PR

on:
  pull_request:
    types: [edited, opened, synchronize]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Get associated issue number
        id: get_issue_number
        run: |
          ISSUE_NUMBERS=$(echo "${{ github.event.pull_request.body }}" | grep -oE "#[0-9]+" | tr -d "#" | tr '\n' ',')
          ISSUE_NUMBERS=$(echo $ISSUE_NUMBERS | sed 's/,$//')
          echo "ISSUE_NUMBERS=$ISSUE_NUMBERS" >> $GITHUB_ENV
          echo "Issue numbers are $ISSUE_NUMBERS"

      - name: Get labels from issue
        uses: actions/github-script@v7
        id: get_issue_labels
        with:
          script: |
            const issueNumbers = process.env.ISSUE_NUMBERS.split(",");
            let allLabels = new Set();
            for (const issueNumber of issueNumbers) {
              try {
                const { data: { labels } } = await github.rest.issues.get({
                  issue_number: issueNumber,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });
                labels.forEach(label => allLabels.add(label.name));
                console.log(labels);
              } catch (error) {
                console.error(`Error fetching labels for issue #${issueNumber}: `, error);
              }
            }
            console.log("All Labels: ", allLabels);
            if (allLabels.size === 0) {
              console.log("No labels found");
              core.setOutput('labels_empty', 'true');
            } else {
              const sortedLabels = Array.from(allLabels).sort().join(",");
              console.log("Labels: ", sortedLabels);
              core.setOutput('labels_empty', 'false');
              core.setOutput('labels', sortedLabels);
            }

      - name: Check if labels are the same
        id: check_labels_are_same
        if: steps.get_issue_labels.outputs.labels_empty == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const issueLabels = "${{ steps.get_issue_labels.outputs.labels }}".split(",");
            const prLabels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            console.log(prLabels);
            const prLabelsNames = prLabels.data.map(label => label.name).sort();
            const customLabels = prLabelsNames.filter(label => !issueLabels.includes(label));
            const combinedLabels = Array.from(new Set([...issueLabels, ...customLabels])).sort().join(",");
            console.log("Combined Labels: ", combinedLabels);
            const isSame = combinedLabels === prLabelsNames.join(",");
            core.setOutput('isSame', isSame.toString());
            core.setOutput('labels', combinedLabels);

      - name: Apply labels to PR
        if: steps.check_labels_are_same.outputs.isSame == 'false'
        uses: actions/github-script@v7
        with:
          script: |
            const isSame = "${{ steps.check_labels_are_same.outputs.isSame }}";
            console.log("Is same: ", isSame);
            const labels = "${{ steps.check_labels_are_same.outputs.labels }}";
            console.log("Applying labels: ", labels);
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels.split(","),
            });
